services:
  app:
    container_name: user-management
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3500:3500"
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    container_name: user_db
    restart: always
    ports:
      - "5432:5432"
    # env_file:
    #   - .env
    environment:  
      DB_HOST: postgres 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mole
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: