services:
  app:
    container_name: user-management
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "npm run prisma:migrate:deploy && npm run start:prod"

  postgres:
    image: postgres:17
    container_name: user_db
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    
    ports:
      - "5432:5432"
    # env_file:
    #   - .env
    environment:  
      DB_HOST: postgres 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mole
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: